---
- name: EXTRAS-OPTIONAL-DEV-JAVA - Install java tools
  ansible.builtin.include_tasks: extras-optional-dev-java.yml
  when: enable_extras_optional_dev_java

- name: EXTRAS-OPTIONAL-DEV-LATEX - Install latex tools
  ansible.builtin.include_tasks: extras-optional-dev-latex.yml
  when: enable_extras_optional_dev_latex

- name: EXTRAS-OPTIONAL-DEV-DOTNET - Install dotnet tools
  ansible.builtin.include_tasks: extras-optional-dev-dotnet.yml
  when: enable_extras_optional_dev_dotnet

- name: EXTRAS-OPTIONAL-DEV-UNITY - Install unity tools
  ansible.builtin.include_tasks: extras-optional-dev-unity.yml
  when: enable_extras_optional_dev_unity

- name: EXTRAS-OPTIONAL-DEV-ESPIDF - Install esp-idf tools
  ansible.builtin.include_tasks: extras-optional-dev-espidf.yml
  when: enable_extras_optional_dev_espidf

- name: EXTRAS-OPTIONAL-DEV-LMSTUDIO - Install lmstudio tools
  ansible.builtin.include_tasks: extras-optional-dev-lmstudio.yml
  when: enable_extras_optional_dev_lmstudio
