---
- name: EXTRAS-COMMON-BACKUP - Create ssh folder
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: "{{ user.home }}/.ssh/"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0700"

- name: EXTRAS-COMMON-BACKUP - Sync ssh keys
  ansible.posix.synchronize:
    src: "{{ src_backup_ssh }}/keys/"
    dest: "{{ user.home }}/.ssh/"
    recursive: true
    delete: false
  become: true
  become_user: "{{ user.name }}"

- name: EXTRAS-COMMON-BACKUP - Sync ssh config
  ansible.posix.synchronize:
    src: "{{ src_backup_ssh }}/config/"
    dest: "{{ user.home }}/.ssh/"
    recursive: true
    delete: false
  become: true
  become_user: "{{ user.name }}"

- name: EXTRAS-COMMON-BACKUP - Sync ssh authorized keys
  ansible.posix.synchronize:
    src: "{{ src_backup_ssh }}/authorized/"
    dest: "{{ user.home }}/.ssh/"
    recursive: true
    delete: false
  become: true
  become_user: "{{ user.name }}"

# - name: EXTRAS-COMMON-BACKUP - Copy user settings
#   when: backup_persist_firefox
#   block:
#     - name: EXTRAS-COMMON-BACKUP - Find Firefox profile directory
#       become: true
#       become_user: "{{ user.name }}"
#       ansible.builtin.find:
#         paths: "{{ user.home }}/.mozilla/firefox"
#         patterns: "*.default*"
#         file_type: directory
#       register: firefox_profiles
#
#     - name: EXTRAS-COMMON-BACKUP - Set profile dir (first match)
#       set_fact:
#         firefox_profile_dir: "{{ firefox_profiles.files[0].path }}"
#       when: firefox_profiles.matched > 0
#
#     # Check if Firefox profile dir exists
#     - name: EXTRAS-COMMON-BACKUP - Check Firefox profile dir
#       ansible.builtin.stat:
#         path: "{{ firefox_profile_dir }}"
#       register: firefox_profile_dir_stat
#       become: true
#       become_user: "{{ user.name }}"
#
#     # Check if backup file exists
#     - name: EXTRAS-COMMON-BACKUP - Check backup places.sqlite
#       ansible.builtin.stat:
#         path: "{{ src_backup }}/firefox/places.sqlite"
#       register: firefox_backup_stat
#
#     # Copy only if BOTH exist
#     - name: EXTRAS-COMMON-BACKUP - Copy bookmarks file into profile
#       become: true
#       become_user: "{{ user.name }}"
#       when:
#         - firefox_profiles.matched > 0
#         - firefox_profile_dir_stat.stat.exists
#         - firefox_backup_stat.stat.exists
#       ansible.builtin.copy:
#         src: "{{ src_backup }}/firefox/places.sqlite"
#         dest: "{{ firefox_profile_dir }}/places.sqlite"
#         owner: "{{ user.name }}"
#         group: "{{ user.name }}"
#         mode: "0600"

- name: Backup Brave bookmarks
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: "{{ src_backup }}/brave/Bookmarks"
    dest: "{{ user.home }}/.config/BraveSoftware/Brave-Browser/Default/Bookmarks"
    mode: "0600"
  when: backup_persist_brave

- name: EXTRAS-COMMON-BACKUP - Copy homedir
  ansible.posix.synchronize:
    src: "{{ src_backup }}/home/"
    dest: "{{ user.home }}/"
    recursive: true
    delete: false
  become: true
  become_user: "{{ user.name }}"
