- name: INIT-COMMON-FM - Optional file managers
  ansible.builtin.apt:
    name:
      - fd-find
      - fzf
      - ranger
      - zoxide
      - plocate
    state: present
  become: true

- name: INIT-COMMON-FM - Optional file managers
  ansible.builtin.shell:
    cmd: "updatedb.plocate"
  become: true
