---
- name: INIT-MAIN - Include base packages
  ansible.builtin.include_tasks: init-base.yml
  when: enable_base

- name: INIT-MAIN - Include common packages
  ansible.builtin.include_tasks: init-common.yml
  when: enable_common

- name: INIT-MAIN - Include optional packages
  ansible.builtin.include_tasks: init-optional.yml
  when: enable_optional
