---
# -- Component Configuration
# Base
enable_extras_base: true
enable_extras_base_essentials: true
# Common
enable_extras_common: true
enable_extras_common_backup: true
enable_extras_common_gaming: false
enable_extras_common_gaming_essentials: true
enable_extras_common_gaming_dxvk: true
enable_extras_common_gaming_gaming: true
enable_extras_common_gaming_steam: true
enable_extras_common_gaming_lutris: true

# Optional
enable_extras_optional: false
enable_extras_optional_dev: true
enable_extras_optional_dev_java: true
enable_extras_optional_dev_latex: false
enable_extras_optional_dev_dotnet: true
enable_extras_optional_dev_unity: true

# -- Source files
src_etcfiles: "../files/etc"
# src_backup: "/media/disks/backup/backup/backup_otr"
# src_backup_sshkeys: "/media/disks/backup/backup/backup_otr/ssh/keys"
src_backup: "~/backup/backup_otr"
src_backup_ssh: "~/backup/backup_otr/ssh"

# -- Destination files
dst_unity_key: "/usr/share/keyrings/Unity_Technologies_ApS.gpg"
dst_dxvk_repo: "/opt/dxvk"

# -- Urls
url_dotnet: "https://dot.net/v1/dotnet-install.sh"
url_dotnet_installer: "https://dot.net/v1/dotnet-install.sh"
url_unity_key: "https://hub.unity3d.com/linux/keys/public"
url_unity_repo: "https://hub.unity3d.com/linux/repos/deb"
url_deb_vscode: "https://go.microsoft.com/fwlink/?LinkID=760868"
url_dxvk_repo: "https://github.com/doitsujin/dxvk.git"
url_lutris_repo: "https://download.opensuse.org/repositories/home:/strycore/Debian_13/"
url_lutris_sources: "/etc/apt/sources.list.d/lutris.list"
url_lutris_key_url: "https://download.opensuse.org/repositories/home:/strycore/Debian_13/Release.key"
url_lutris_key_path: "/etc/apt/keyrings/lutris.gpg"

# -- Backup options
backup_persist_ssh_keys: true
backup_persist_ssh_config: true
backup_persist_ssh_authorized: true
backup_persist_firefox: true
backup_persist_brave: true
backup_persist_nerdtree: true
