---
# -- Component Configuration
# Base
enable_desktop_base: true
enable_desktop_base_essentials: true
# Common
enable_desktop_common: true
enable_desktop_common_x11: true
enable_desktop_common_rofi: true
enable_desktop_common_qtile: true
# Optional
enable_desktop_optional: true
enable_desktop_optional_gnometools: true
enable_desktop_optional_brave: true

# -- Source files
src_dotfiles: "../files/dotfiles"
src_etcfiles: "../files/etc"
src_scripts: "../files/scripts"

# --Destination files
dst_qtile_repo: "/usr/share/mps/tools/qtile"
dst_rofi_snippets: "/usr/share/rofi"
dst_brave_keyring: "/usr/share/keyrings/brave-browser-archive-keyring.gpg"

# -- Urls
url_qtile: "https://github.com/qtile/qtile"
url_brave_repo: "https://brave-browser-apt-release.s3.brave.com/"

# -- qtile
dst_venv_qtile: "~/.venvs/default"
