---
# -- Component Configuration
# Base
enable_services_base: true
# Common
enable_services_common: true
enable_services_common_docker: true
# Optional
enable_services_optional: true

# -- Source files
src_templates: "../files/templates/"

# -- Destination files
dst_docker_keyring_dir: /etc/apt/keyrings
dst_docker_key: /etc/apt/keyrings/docker.asc
dst_docker_list: /etc/apt/sources.list.d/docker.list
dst_docker_root: /srv/docker
dst_docker_config: /etc/docker

# -- Urls
url_docker_gpg: https://download.docker.com/linux/debian/gpg
url_docker_repo: https://download.docker.com/linux/debian
