---
- name: TERMINAL-MAIN-FACTS - Prepare user facts
  ansible.builtin.include_tasks: facts-terminal-user.yml

- name: TERMINAL-MAIN - Include terminal base installers
  ansible.builtin.include_tasks: terminal.yml
  loop: "{{ users_present }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    user: "{{ item }}"
- name: TERMINAL-MAIN - Include report
  ansible.builtin.include_tasks: terminal-report.yml
