---
- name: TERMINAL-BASE-ESSENTIALS - Install essentials
  ansible.builtin.include_tasks: terminal-base-essentials.yml
  when: enable_terminal_base_essentials

- name: TERMINAL-BASE-BASH - Install bash
  ansible.builtin.include_tasks: terminal-base-bash.yml
  when: enable_terminal_base_bash

- name: TERMINAL-BASE-VIM - Install vim
  ansible.builtin.include_tasks: terminal-base-vim.yml
  when: enable_terminal_base_vim

- name: TERMINAL-BASE-SCRIPTS - Copy scripts
  ansible.builtin.include_tasks: terminal-base-scripts.yml
  when: enable_terminal_base_scripts

- name: TERMINAL-BASE-SKELETONS - Copy skeletons
  ansible.builtin.include_tasks: terminal-base-skeletons.yml
  when: enable_terminal_base_skeletons
