enable_init: "false"

# Optionals
enable_optionals: "true"
enable_optionals_archives: "true"
enable_optionals_build: "true"
enable_optionals_fm: "true"
enable_optionals_networking: "true"
enable_optionals_stats: "true"
enable_optionals_terminal: "true"

# Hardening
enable_harden: "true"
enable_harden_apparmor: "true"
enable_harden_auditing: "true"
enable_harden_firewall: "true"

# tools
enable_terminal: "true"
enable_bash: "true"
enable_tmux: "true"
enable_vim: "true"
enable_nvim: "true"
enable_rust: "true"
enable_yazi: "true"

# users
enable_useradd: "true"
enable_userdel: "true"
