---
# SERVICES
## SERVICES: Install common services
### SERVICES: Prepare facts
- name: Prepare user facts
  ansible.builtin.include_tasks: create-facts-users.yml

### TOOLS: Install docker
- name: Install docker
  ansible.builtin.include_tasks: install-docker.yml
