---
- name: INIT - Essential packages
  ansible.builtin.apt:
    name:
      - sudo
      - curl
      - wget
      - rsync
      - gnupg
      - lsb-release
      - debconf
      - debconf-utils
      - fontconfig
      - psutils
      - psmisc
      - htop
      - rsyslog
      - bsdmainutils
    state: present
  become: true
