---
- name: OPTIONALS - Optional terminal tools
  ansible.builtin.apt:
    name:
      - cowsay
      - figlet
      - fortune
      - fortunes-de
      - cmatrix
      - kitty
      - tmux
      - tmuxinator
    state: present
  become: true
