---
- name: OPTIONALS - Optional networking tools
  ansible.builtin.apt:
    name:
      - net-tools
      - bind9-dnsutils
      - bridge-utils
      - iptables
      - tcpdump
      - uml-utilities
      - traceroute
      - netcat-traditional
      - iw
      - ssh
      - nmap
      - dnsutils
      - isc-dhcp-client
    state: present
  become: true
