---
- name: HARDEN-MAIN - Include base hardening packages
  ansible.builtin.include_tasks: harden-base.yml
  when: enable_harden_base

- name: HARDEN-MAIN - Include common hardening packages
  ansible.builtin.include_tasks: harden-common.yml
  when: enable_harden_common

- name: HARDEN-MAIN - Include optional hardening packages
  ansible.builtin.include_tasks: harden-optional.yml
  when: enable_harden_optional
