---
- name: HARDEN-MAIN-FACTS - Prepare user facts
  ansible.builtin.include_tasks: facts-harden-user.yml

- name: HARDEN-MAIN - Include hardening
  ansible.builtin.include_tasks: harden.yml
  loop: "{{ users_present }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    user: "{{ item }}"

- name: HARDEN-MAIN - Include report
  ansible.builtin.include_tasks: harden-report.yml
