---
- name: INIT - Essentials os packages
  ansible.builtin.apt:
    name:
      - openssh-client
    state: present
  become: true

- name: INIT - Copy ssh config
  ansible.builtin.template:
    src: "{{ src_etcfiles }}/ssh/ssh_config"
    dest: "/etc/ssh/ssh_config"
    owner: "root"
    group: "root"
    mode: "0744"

- name: Ensure SSH service is running
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true
  become: true
