---
- name: OPTIONALS - Optional build tools
  ansible.builtin.apt:
    name:
      - gcc
      - gdb
      - lldb
      - build-essential
      - check
      - flex
      - bison
      - automake
    state: present
  become: true
