---
- name: Check if cargo yazi is already installed
  ansible.builtin.stat:
    path: "{{ user.home }}/.cargo/bin/yazi"
  register: cargo_yazi

- name: Install Cargo yazi only if not already installed
  ansible.builtin.shell: |
    source {{ user.home }}/.cargo/env
    cargo install cargo-binstall
    cargo binstall yazi-fm yazi-cli --no-confirm
  args:
    executable: /bin/bash
  environment:
    CARGO_HOME: "{{ user.home }}/.cargo"
    PATH: "{{ user.home }}/.cargo/bin:{{ ansible_env.PATH }}"
  when: not cargo_yazi.stat.exists
  become: true
  become_user: "{{ user.name }}"
