---
# TOOLS
## TOOLS: Install common tools
### TOOLS: Prepare facts
- name: Prepare user facts
  ansible.builtin.include_tasks: create-facts-users.yml

### TOOLS: Install bash essentials
- name: Include common installers
  ansible.builtin.include_tasks: install.yml
  loop: "{{ users_present }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    user: "{{ item }}"
