---
- name: rust essential packages
  ansible.builtin.apt:
    name:
      - clang
    state: present
  become: true

- name: Ensure Rustup directory exists
  ansible.builtin.file:
    path: "{{ dst_tools }}/rustup"
    state: directory
    mode: "0755"

- name: Download rustup installation script
  ansible.builtin.get_url:
    url: "{{ url_rustup }}"
    dest: "{{ dst_rustup_sh }}"
    mode: "0755"

- name: Enlarge tmpfs
  ansible.builtin.shell:
    cmd: "sudo mount -o size=10G,remount /tmp"

- name: Run rustup installation script if not already installed
  ansible.builtin.shell:
    cmd: "{{ dst_rustup_sh }} -y"
    creates: "{{ user.home }}/.cargo/env"
  become: true
  become_user: "{{ user.name }}"

- name: Add Rust to PATH in .bashrc if not already present
  ansible.builtin.lineinfile:
    path: "{{ user.home }}/.bashrc"
    line: 'export PATH="$PATH:$HOME/.cargo/bin"'
    state: present
    insertafter: EOF
  become: true
  become_user: "{{ user.name }}"

- name: Source Rust env in .bashrc if not already present
  ansible.builtin.lineinfile:
    path: "{{ user.home }}/.bashrc"
    line: 'source "$HOME"/.cargo/env'
    state: present
    insertafter: EOF
  become: true
  become_user: "{{ user.name }}"

- name: Check if cargo tools are already installed
  ansible.builtin.stat:
    path: "{{ user.home }}/.cargo/bin/fd"
  register: cargo_fd

- name: Install Cargo tools only if not already installed
  ansible.builtin.shell: |
    source {{ user.home }}/.cargo/env
    cargo install fd-find tree-sitter-cli
  args:
    executable: /bin/bash
  environment:
    CARGO_HOME: "{{ user.home }}/.cargo"
    PATH: "{{ user.home }}/.cargo/bin:{{ ansible_env.PATH }}"
  when: not cargo_fd.stat.exists
  become: true
  become_user: "{{ user.name }}"
