### TOOLS: Install bash
- name: Install bash essentials
  ansible.builtin.include_tasks: install-bash.yml
  when: enable_bash == "true"

### TOOLS: Install bash
- name: Install bash essentials
  ansible.builtin.include_tasks: install-terminal.yml
  when: enable_terminal == "true"

### TOOLS: Install rust
- name: Install rust environment
  ansible.builtin.include_tasks: install-rust.yml
  when: enable_rust == "true"

### TOOLS: Install rust
- name: Install rust-yazi
  ansible.builtin.include_tasks: install-yazi.yml
  when: enable_yazi == "true"

  ### TOOLS: Install vim
- name: Install essential tmux packlages
  ansible.builtin.include_tasks: install-tmux.yml
  when: enable_tmux == "true"

### TOOLS: Install vim
- name: Install common vim stuff
  ansible.builtin.include_tasks: install-vim.yml
  when: enable_vim == "true"

### TOOLS: Install nvim
- name: Install common nvim stuff
  ansible.builtin.include_tasks: install-nvim.yml
  when: enable_nvim == "true"
