---
# -- Component Configuration
# manage Users
enable_users_add: true
enable_users_del: true
enable_users_groups_add: true

# Print passwords being generated in plain text to stdout
user_print_passwords_plaintext: false

# Sudo
sudo_macros:
  ADMIN_DEFAULT:
    - "/usr/bin/apt update *"
    - "/usr/bin/systemctl daemon-reload"
    - "/usr/bin/systemctl status *"
    - "/usr/bin/systemctl list-units *"
    - "/usr/bin/systemctl list-timers *"
    - "/usr/bin/journalctl *"
    - "/usr/bin/journalctl -u *"
    - "/usr/bin/systemctl show *"
    - "/usr/bin/df *"
    - "/usr/bin/du *"
    - "/usr/sbin/lsblk *"
    - "/usr/bin/netstat *"
    - "/usr/bin/which *"
    - "/usr/bin/cat /etc/hosts"
    - "/usr/bin/cat /etc/resolv.conf"
    - "/usr/bin/cat /etc/network/interfaces"
    - "/usr/sbin/route -n"
    - "/usr/sbin/iptables -L *"
    - "/usr/sbin/brctl show *"
    - "/usr/bin/systemctl restart"
    - "/usr/sbin/poweroff"
    - "/usr/sbin/reboot"
  ADMIN_DEBUG:
    - "/bin/sh *"
    - "/bin/bash *"
    - "/usr/bin/apt *"
    - "/usr/lib/apt/methods/http *"
    - "/usr/bin/tee *"
    - "/usr/bin/batcat *"
    - "/usr/bin/cat *"
    - "/usr/bin/vi *"
    - "/usr/bin/vim *"
    - "/usr/bin/nano *"
    - "/usr/sbin/route *"
    - "/usr/sbin/iptables *"
    - "/usr/sbin/brctl *"
