---
- name: Create sudo macros file
  template:
    src: ../files/templates/macro.j2
    dest: "/etc/sudoers.d/00_macros"
    owner: root
    group: root
    mode: "0440"
  vars:
    macros: "{{ sudo_macros }}"

- name: Ensure sudoers file for each user
  template:
    src: ../files/templates/sudoers.j2
    dest: "/etc/sudoers.d/{{ item.name }}"
    owner: root
    group: root
    mode: "0440"
  loop: "{{ users_present }}"
  when: item.sudo is defined
  vars:
    user: "{{ item }}"
