---
- name: Build users list with passwords and hashes
  set_fact:
    users_with_passwords: "{{ users_with_passwords | default([]) + [ user_with_pw ] }}"
  vars:
    generated_pw: >-
      {{ (item.password if (item.password is defined and item.password | length > 0)
         else lookup('password','/dev/null length=16 chars=ascii_letters,digits,punctuation')) | trim }}

    user_with_pw: >-
      {{
        item | combine({
          'password_plain': generated_pw,
          'password_hash': (
             generated_pw if generated_pw.startswith('$6$') else generated_pw | password_hash('sha512')
          )
        })
      }}
  loop: "{{ users_present }}"
  loop_control:
    label: "{{ item.name }}"

- name: Replace users with updated version
  set_fact:
    users_present: "{{ users_with_passwords | default([]) }}"
