---
- name: Prepare user facts
  ansible.builtin.include_tasks: create-facts-users.yml

- name: Prepare password facts
  ansible.builtin.include_tasks: create-facts-password.yml

- name: Manage creation
  ansible.builtin.include_tasks: add-user.yml
  loop: "{{ users_present }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    user_data: "{{ item }}"
  when: enable_useradd == "true"

- name: Manage user deletion
  ansible.builtin.include_tasks: del-user.yml
  loop: "{{ users_absent }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    user_data: "{{ item }}"
  when: enable_userdel == "true"
