---
- name: DESKTOP-BASE-ESSENTIALS - Install desktop essentials
  ansible.builtin.apt:
    name:
      - galculator
      - arandr
      - iw
      - xcwd
      - espeak
      - lxde-icon-theme
      - thunderbird
      - firefox-esr
      - evince
    state: present
  become: true

- name: DESKTOP-BASE-ESSENTIALS-SOUND - Install desktop sound essentials
  ansible.builtin.apt:
    name:
      - pulseaudio
      - pavucontrol
      - volumeicon-alsa
      - vorbis-tools
      - libmpg123-dev
    state: present
  become: true

- name: DESKTOP-BASE-ESSENTIALS - Copy Config
  ansible.posix.synchronize:
    src: "{{ src_dotfiles }}/{{ file }}"
    dest: "{{ user.home }}/{{ file }}"
    recursive: true
    delete: false
  loop: "{{ desktop_dotfiles_essentials }}"
  loop_control:
    loop_var: "file"
  when: desktop_dotfiles_essentials is defined
  become: true
  become_user: "{{ user.name }}"

- name: DESKTOP-BASE-ESSENTIALS - Copy scripts
  ansible.posix.synchronize:
    src: "{{ src_scripts }}/{{ file }}"
    dest: "{{ user.home }}/.local/bin/{{ file }}"
    recursive: true
    delete: false
  loop: "{{ desktop_scripts_autostart }}"
  loop_control:
    loop_var: "file"
  when: desktop_scripts_autostart is defined
  become: true
  become_user: "{{ user.name }}"

- name: DESKTOP-BASE-ESSENTIALS - Create folders
  ansible.builtin.file:
    path: "{{ dst_images }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: DESKTOP-BASE-ESSENTIALS - Copy Images
  ansible.posix.synchronize:
    src: "{{ src_images }}"
    dest: "{{ dst_images }}"
    recursive: true
    delete: false
  become: true
