---
- name: DESKTOP-BASE-THUNAR - Install thunar essentials
  ansible.builtin.apt:
    name:
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-volman
      - thunar-gtkhash
      - xfce4-goodies
      - xfce4-places-plugin
      - thunar-font-manager
      - thunarx-python
    state: present
  become: true

- name: DESKTOP-BASE-THUNAR - Copy Config
  ansible.builtin.copy:
    src: "{{ src_dotfiles }}/{{ file }}"
    dest: "{{ user.home }}/{{ file }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0700"
  loop: "{{ desktop_dotfiles_thunar }}"
  loop_control:
    loop_var: "file"
  when: desktop_dotfiles_thunar is defined
