---
- name: DESKTOP-BASE-ESSENTIALS - Install desktop essentials
  ansible.builtin.apt:
    name:
      - galculator
      - numlockx
      - xclip
      - arandr
      - lxappearance
      - psutils
      - iw
      - xcwd
      - zoxide
      - kitty
      - tilda
      - thunderbird
      - firefox-esr
      - evince
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-volman
      - thunar-gtkhash
      - xfce4-goodies
      - xfce4-places-plugin
      - thunar-font-manager
      - thunarx-python
      - ssh-askpass
      - plymouth
      - plymouth-themes
    state: present
  become: true

- name: DESKTOP-BASE-ESSENTIALS - Install essentials for window manager
  ansible.builtin.apt:
    name:
      - feh
      - lightdm
      - picom
      - xbacklight
      - pulseaudio
      - pavucontrol
      - volumeicon-alsa
      - libmpg123-dev
      - lxde-icon-theme
      - dconf-cli
      - dconf-editor
      - dunst

    state: present
  become: true

