---
# -- Component Configuration
# Base
enable_optimize_base: true
enable_optimize_base_essentials: true
# Common
enable_optimize_common: true
# Optional
enable_optimize_optional: true
enable_optimize_optional_zram: true
enable_optimize_optional_ramdisks: true
enable_optimize_optional_kmscon: true

# -- zram
optimize_zram_percentage: 10

# -- ramdisk
create_ramdisk_varlog: true

# -- Source files
src_etcfiles: "../files/etc"

# -- Destination files

