---
- name: Setup base os (Debian)
  hosts: target_hosts
  become: true
  vars_files:
    - "../roles/baseos/vars/vars_baseos.yml"
    - "../roles/usermanager/vars/vars_user.yml"
    - "../roles/installer-terminal/vars/vars_tools_terminal.yml"
    - "../roles/installer-terminal/vars/vars_tools_services.yml"
  roles:
    - baseos
    - usermanager
    - installer-terminal
    - installer-services
