---
- name: Setup base os (Debian)
  hosts: target_hosts
  become: true
  vars:
    enable_init: "false"

    # Optionals
    enable_optionals: "false"
    enable_optionals_archives: "true"
    enable_optionals_build: "true"
    enable_optionals_fm: "true"
    enable_optionals_networking: "true"
    enable_optionals_stats: "true"
    enable_optionals_terminal: "true"

    # Hardening
    enable_harden: "true"
    enable_harden_apparmor: "false"
    enable_harden_auditing: "false"
    enable_harden_firewall: "true"
  vars_files:
    - "../roles/baseos-debian/vars/vars.yml"
  roles:
    - baseos-debian
