---
user_print_plain: true

users:
  - name: alice
    # uid: 1000
    # gid: 1000
    group: "alice"
    home: /home/alice
    groups: ["admin", "config", "foobar"]
    append_groups: true
    comment: "Alice Admin"
    shell: /bin/bash
    create_home: true
    system: false
    expires: -1
    # password: ""
    password: "alicepass"
    # password: "$6$rounds=656000$TyhD0QYWPJgvbaOz$D6N9XwQNhlmUi2h4.Fp7CMBvAqr1b/uTBzCn2fO9Pd1aeFxdeDUSO2y.o./CHqD5sLUBW.veBRVLNGl7n2OLG1"
    state: present
    ssh_keys:
      - name: id_rsa
        path: ../vars/dummy/id_rsa
        # content: "-----BEGIN RSA PRIVATE KEY-----..."
      - name: id_rsa.pub
        path: ../vars/dummy/id_rsa.pub
        # content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC..."
    authorized_keys:
      - path: ../vars/dummy/authorized_keys
      # - content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC..."
